# Module 4: Selecting Data in Pandas (Indexing & Filtering)
### 🚢 Using the Kaggle Titanic Dataset

## 1️⃣ Introduction

In data analysis, we rarely use the **entire dataset at once**.
Most of the time, we need to **select specific rows, columns, or filtered data**.

For example, on the Titanic dataset:

- Select only the **Name column**
- Select passengers with **Fare greater than 100**
- Select the **first few rows of data**
- Select rows based on **conditions** (e.g., only female passengers)

Pandas provides several powerful methods to select data:

1️⃣ Column Selection  
2️⃣ Row Selection  
3️⃣ `loc[]` (Label-based selection)  
4️⃣ `iloc[]` (Position-based selection)  
5️⃣ Boolean Filtering  

These methods are used **daily in real-world data analysis**.

## 2️⃣ Why This Concept is Important

The Titanic dataset has **891 rows and 12 columns**.

A data analyst may need to:

✔ Find passengers who **survived**  
✔ Extract **only the Name and Fare columns**  
✔ Get **specific rows** to inspect individual records  
✔ Filter **female passengers in 1st class**  

To perform these tasks efficiently, we use **Pandas selection methods**.

## 3️⃣ Load the Titanic Dataset

In [1]:
import pandas as pd

# Load the Titanic dataset


df = pd.read_csv("Titanic-Dataset.csv")

print("Shape:", df.shape)
df.head()

Shape: (891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
# Check all available columns
print(df.columns.tolist())

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

## 4️⃣ Selecting Columns

### Select One Column

Use `df["column_name"]` to select a single column.
Pandas returns a **Series** object.

In [3]:
# Select the 'Name' column — returns a Series
df["Name"].head(10)

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: str

In [4]:
# Select the 'Fare' column
df["Fare"].head(10)

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
5     8.4583
6    51.8625
7    21.0750
8    11.1333
9    30.0708
Name: Fare, dtype: float64

### Select Multiple Columns

Use **double brackets** `df[["col1", "col2"]]` to select multiple columns.
This returns a **DataFrame**.

In [5]:
# Select Name and Fare columns — returns a DataFrame
df[["Name", "Fare"]].head(10)

                                                Name     Fare
0                            Braund, Mr. Owen Harris   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833
2                             Heikkinen, Miss. Laina   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  53.1000
4                           Allen, Mr. William Henry   8.0500
5                                   Moran, Mr. James   8.4583
6                            McCarthy, Mr. Timothy J  51.8625
7                     Palsson, Master. Gosta Leonard  21.0750
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  11.1333
9                Nasser, Mrs. Nicholas (Adele Achem)  30.0708

In [6]:
# Select Name, Sex, Age, and Survived columns
df[["Name", "Sex", "Age", "Survived"]].head(10)

                                                Name     Sex   Age  Survived
0                            Braund, Mr. Owen Harris    male  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0         1
2                             Heikkinen, Miss. Laina  female  26.0         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0         1
4                           Allen, Mr. William Henry    male  35.0         0
5                                   Moran, Mr. James    male   NaN         0
6                            McCarthy, Mr. Timothy J    male  54.0         0
7                     Palsson, Master. Gosta Leonard    male   2.0         0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0         1
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0         1

## 5️⃣ Selecting Rows

Rows can be selected using **index slicing** with the format `df[start:stop]`.

The stop index is **not included**.

In [7]:
# Select the first 5 rows (index 0 to 4)
df[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
# Select rows 10 to 14
df[10:15]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

## 6️⃣ Using `loc[]` — Label-Based Selection

`loc[]` selects data using **row labels and column names**.

Syntax: `df.loc[row_label, column_name]`

In [9]:
# Select the entire row at label 0 — first passenger
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [10]:
# Select a specific value: Name of the passenger at row 0
df.loc[0, "Name"]

'Braund, Mr. Owen Harris'

In [11]:
# Select rows 0 to 4, and only Name, Sex, Age, Survived columns
df.loc[0:4, ["Name", "Sex", "Age", "Survived"]]

                                                Name     Sex   Age  Survived
0                            Braund, Mr. Owen Harris    male  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0         1
2                             Heikkinen, Miss. Laina  female  26.0         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0         1
4                           Allen, Mr. William Henry    male  35.0         0

In [12]:
# Select rows 5 to 9, and Pclass, Fare, Embarked columns
df.loc[5:9, ["Pclass", "Fare", "Embarked"]]

   Pclass     Fare Embarked
5       3   8.4583        Q
6       1  51.8625        S
7       3  21.0750        S
8       3  11.1333        S
9       2  30.0708        C

## 7️⃣ Using `iloc[]` — Position-Based Selection

`iloc[]` selects data based on **numerical index positions** (0-based).

Syntax: `df.iloc[row_position, column_position]`

In [13]:
# Select the entire first row by position
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [14]:
# Select a specific cell: row 0, column 3 (Name column)
# 0 → first row,  3 → 4th column (Name)
# print("Column positions:")
# for i, col in enumerate(df.columns):
#     print(f"  {i} → {col}")

In [15]:
# Get the Name of the first passenger using position
df.iloc[0, 3]

'Braund, Mr. Owen Harris'

In [16]:
# Select first 5 rows and first 4 columns using positions
df.iloc[0:5, 0:4]

,PassengerId,Survived,Pclass,Name
0,1,0,3,"Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,3,"Allen, Mr. William Henry"

In [17]:
# Select rows 10–14 and columns 2, 3, 4 (Pclass, Name, Sex)
df.iloc[10:15, 2:5]

    Pclass                                  Name     Sex
10       3       Sandstrom, Miss. Marguerite Rut  female
11       1              Bonnell, Miss. Elizabeth  female
12       3        Saundercock, Mr. William Henry    male
13       3           Andersson, Mr. Anders Johan    male
14       3  Vestrom, Miss. Hulda Amanda Adolfina  female

### `loc[]` vs `iloc[]` — Quick Comparison

| Feature      | `loc[]`                    | `iloc[]`                    |
| ------------ | -------------------------- | --------------------------- |
| Based on     | **Labels** (column names)  | **Positions** (numbers)     |
| Row input    | Row label / index name     | Integer position (0, 1, 2)  |
| Column input | Column name string         | Integer position (0, 1, 2)  |
| Slice end    | **Inclusive**              | **Exclusive**               |

## 8️⃣ Boolean Filtering (Conditional Selection)

We can filter rows based on **conditions**.

The condition creates a **True/False (boolean) Series**, and Pandas returns only the rows where the condition is **True**.

In [18]:
# See what the boolean condition looks like internally
(df["Fare"] > 100).head(10)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Fare, dtype: bool

In [19]:
# Filter passengers who paid Fare > 100
df[df["Fare"] > 100][["Name", "Pclass", "Fare", "Survived"]].head(10)

,Name,Pclass,Fare,Survived
27,"Fortune, Mr. Charles Alexander",1,263.0000,0
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",1,146.5208,1
88,"Fortune, Miss. Mabel Helen",1,263.0000,1
118,"Baxter, Mr. Quigg Edmond",1,247.5208,0
195,"Lurette, Miss. Elise",1,146.5208,1
215,"Newell, Miss. Madeleine",1,113.2750,1
258,"Ward, Miss. Anna",1,512.3292,1
268,"Graham, Mrs. William Thompson (Edith Junkins)",1,153.4625,1
269,"Bissette, Miss. Amelia",1,135.6333,1
297,"Allison, Miss. Helen Loraine",1,151.5500,0

In [20]:
# Filter only passengers who SURVIVED (Survived == 1)
df[df["Survived"] == 1][["Name", "Sex", "Age", "Pclass"]].head(10)

                                                 Name     Sex   Age  Pclass
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0       1
2                              Heikkinen, Miss. Laina  female  26.0       3
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0       1
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0       3
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0       2
10                    Sandstrom, Miss. Marguerite Rut  female   4.0       3
11                           Bonnell, Miss. Elizabeth  female  58.0       1
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0       2
17                       Williams, Mr. Charles Eugene    male   NaN       2
19                            Masselmani, Mrs. Fatima  female   NaN       3

In [21]:
# Filter only FEMALE passengers
df[df["Sex"] == "female"][["Name", "Age", "Pclass", "Survived"]].head(10)

                                                 Name   Age  Pclass  Survived
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1         1
2                              Heikkinen, Miss. Laina  26.0       3         1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1         1
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0       3         1
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0       2         1
10                    Sandstrom, Miss. Marguerite Rut   4.0       3         1
11                           Bonnell, Miss. Elizabeth  58.0       1         1
14               Vestrom, Miss. Hulda Amanda Adolfina  14.0       3         0
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0       2         1
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0       3         0

In [22]:
# Filter passengers who embarked from port 'C' (Cherbourg)
df[df["Embarked"] == "C"][["Name", "Pclass", "Fare", "Embarked"]].head(10)

,Name,Pclass,Fare,Embarked
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,71.2833,C
9,"Nasser, Mrs. Nicholas (Adele Achem)",2,30.0708,C
19,"Masselmani, Mrs. Fatima",3,7.2250,C
26,"Emir, Mr. Farred Chehab",3,7.2250,C
30,"Uruchurtu, Don. Manuel E",1,27.7208,C
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",1,146.5208,C
34,"Meyer, Mr. Edgar Joseph",1,82.1708,C
36,"Mamee, Mr. Hanna",3,7.2292,C
39,"Nicola-Yarred, Miss. Jamila",3,11.2417,C
42,"Kraeff, Mr. Theodor",3,7.8958,C

### Multiple Conditions

Combine conditions using `&` (AND) or `|` (OR). Always wrap each condition in **parentheses**.

In [23]:
# Filter: Female passengers who SURVIVED
df[(df["Sex"] == "female") & (df["Survived"] == 1)][["Name", "Age", "Pclass", "Fare"]].head(10)

                                                 Name   Age  Pclass     Fare
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1  71.2833
2                              Heikkinen, Miss. Laina  26.0       3   7.9250
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1  53.1000
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0       3  11.1333
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0       2  30.0708
10                    Sandstrom, Miss. Marguerite Rut   4.0       3  16.7000
11                           Bonnell, Miss. Elizabeth  58.0       1  26.5500
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0       2  16.0000
19                            Masselmani, Mrs. Fatima   NaN       3   7.2250
22                        McGowan, Miss. Anna "Annie"  15.0       3   8.0292

In [24]:
# Filter: 1st class passengers who paid Fare > 100
df[(df["Pclass"] == 1) & (df["Fare"] > 100)][["Name", "Pclass", "Fare", "Survived"]].head(10)

,Name,Pclass,Fare,Survived
27,"Fortune, Mr. Charles Alexander",1,263.0000,0
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",1,146.5208,1
88,"Fortune, Miss. Mabel Helen",1,263.0000,1
118,"Baxter, Mr. Quigg Edmond",1,247.5208,0
195,"Lurette, Miss. Elise",1,146.5208,1
215,"Newell, Miss. Madeleine",1,113.2750,1
258,"Ward, Miss. Anna",1,512.3292,1
268,"Graham, Mrs. William Thompson (Edith Junkins)",1,153.4625,1
269,"Bissette, Miss. Amelia",1,135.6333,1
297,"Allison, Miss. Helen Loraine",1,151.5500,0

In [25]:
# Filter: Passengers who were either in 1st class OR survived
df[(df["Pclass"] == 1) | (df["Survived"] == 1)][["Name", "Pclass", "Survived"]].head(10)

                                                 Name  Pclass  Survived
1   Cumings, Mrs. John Bradley (Florence Briggs Th...       1         1
2                              Heikkinen, Miss. Laina       3         1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)       1         1
6                             McCarthy, Mr. Timothy J       1         0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)       3         1
9                 Nasser, Mrs. Nicholas (Adele Achem)       2         1
10                    Sandstrom, Miss. Marguerite Rut       3         1
11                           Bonnell, Miss. Elizabeth       1         1
15                   Hewlett, Mrs. (Mary D Kingcome)        2         1
17                       Williams, Mr. Charles Eugene       2         1

## 🌍 Real-World Example — Titanic Analysis Workflow

Combining all selection techniques in a realistic analysis scenario.

In [26]:
# ✔ Task 1: Extract only Name and Fare columns
df[["Name", "Fare"]].head()

                                                Name     Fare
0                            Braund, Mr. Owen Harris   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833
2                             Heikkinen, Miss. Laina   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  53.1000
4                           Allen, Mr. William Henry   8.0500

In [27]:
# ✔ Task 2: Find passengers who did NOT survive
did_not_survive = df[df["Survived"] == 0]
print(f"Total passengers who did not survive: {len(did_not_survive)}")
did_not_survive[["Name", "Sex", "Age", "Pclass"]].head()

Total passengers who did not survive: 549

                             Name   Sex   Age  Pclass
0         Braund, Mr. Owen Harris  male  22.0       3
4        Allen, Mr. William Henry  male  35.0       3
5                Moran, Mr. James  male   NaN       3
6         McCarthy, Mr. Timothy J  male  54.0       1
7  Palsson, Master. Gosta Leonard  male   2.0       3

In [28]:
# ✔ Task 3: Select a specific passenger record using loc[]
print("Passenger at index 5:")
df.loc[5, ["Name", "Sex", "Age", "Pclass", "Survived"]]

Passenger at index 5:

Name        Moran, Mr. James
Sex                     male
Age                      NaN
Pclass                     3
Survived                   0
Name: 5, dtype: object

In [29]:
# ✔ Task 4: Young female survivors (Age < 18, Female, Survived)
young_female_survivors = df[
    (df["Sex"] == "female") &
    (df["Age"] < 18) &
    (df["Survived"] == 1)
]
print(f"Young female survivors: {len(young_female_survivors)}")
young_female_survivors[["Name", "Age", "Pclass", "Fare"]]

Young female survivors: 38

,Name,Age,Pclass,Fare
9,"Nasser, Mrs. Nicholas (Adele Achem)",14.00,2,30.0708
10,"Sandstrom, Miss. Marguerite Rut",4.00,3,16.7000
22,"McGowan, Miss. Anna ""Annie""",15.00,3,8.0292
39,"Nicola-Yarred, Miss. Jamila",14.00,3,11.2417
43,"Laroche, Miss. Simonne Marie Anne Andree",3.00,2,41.5792
58,"West, Miss. Constance Mirium",5.00,2,27.7500
68,"Andersson, Miss. Erna Alexandra",17.00,3,7.9250
84,"Ilett, Miss. Bertha",17.00,2,10.5000
156,"Gilnagh, Miss. Katherine ""Katie""",16.00,3,7.7333
172,"Johnson, Miss. Eleanor Ileen",1.00,3,11.1333
184,"Kink-Heilmann, Miss. Luise Gretchen",4.00,3,22.0250
208,"Carr, Miss. Helen ""Ellen""",16.00,3,7.7500
233,"Asplund, Miss. Lillian Gertrud",5.00,3,31.3875
237,"Collyer, Miss. Marjorie ""Lottie""",8.00,2,26.2500
307,"Penasco y Castellana, Mrs. Victor de Satode (M...",17.00,1,108.9000
329,"Hippach, Miss. Jean Gertrude",16.00,1,57.9792
381,"Nakid, Miss. Maria (""Mary"")",1.00,3,15.7417
389,"Lehmann, Miss. Bertha",17.00,2,12.0000
435,"Carter, Miss. Lucile Polk",14.00,1,120.0000
446,"Mellinger, Miss. Madeleine Violet",13.00,2,19.5000
448,"Baclini, Miss. Marie Catherine",5.00,3,19.2583
469,"Baclini, Miss. Helene Barbara",0.75,3,19.2583
479,"Hirvonen, Miss. Hildur E",2.00,3,12.2875
504,"Maioni, Miss. Roberta",16.00,1,86.5000
530,"Quick, Miss. Phyllis May",2.00,2,26.0000
535,"Hart, Miss. Eva Miriam",7.00,2,26.2500
618,"Becker, Miss. Marion Louise",4.00,2,39.0000
644,"Baclini, Miss. Eugenie",0.75,3,19.2583
689,"Madill, Miss. Georgette Alexandra",15.00,1,211.3375
691,"Karun, Miss. Manca",4.00,3,13.4167
720,"Harper, Miss. Annie Jessie ""Nina""",6.00,2,33.0000
750,"Wells, Miss. Joan",4.00,2,23.0000
777,"Emanuel, Miss. Virginia Ethel",5.00,3,12.4750
780,"Ayoub, Miss. Banoura",13.00,3,7.2292
781,"Dick, Mrs. Albert Adrian (Vera Gillespie)",17.00,1,57.0000
830,"Yasbeck, Mrs. Antoni (Selini Alexander)",15.00,3,14.4542
853,"Lines, Miss. Mary Conover",16.00,1,39.4000
875,"Najib, Miss. Adele Kiamie ""Jane""",15.00,3,7.2250

## 💡 Important Tips

| Syntax                              | Purpose                              |
| ----------------------------------- | ------------------------------------ |
| `df["col"]`                         | Select single column (Series)        |
| `df[["col1", "col2"]]`              | Select multiple columns (DataFrame)  |
| `df[0:5]`                           | Select rows by slice                 |
| `df.loc[row, col]`                  | Label-based row/column selection     |
| `df.iloc[row, col]`                 | Position-based selection             |
| `df[df["col"] > value]`             | Boolean / conditional filtering      |
| `df[(cond1) & (cond2)]`             | Multiple conditions — AND            |
| `df[(cond1) \| (cond2)]`            | Multiple conditions — OR             |

## 📋 Summary of Module 4

In this module we learned how to **select and filter data in Pandas** using the real-world **Titanic dataset**.

Concepts covered:

- **Column selection** → `df["col"]` and `df[["col1", "col2"]]`
- **Row selection** → `df[0:5]`
- **`loc[]`** → label-based selection (inclusive slicing)
- **`iloc[]`** → index position selection (exclusive slicing)
- **Boolean filtering** → single and multi-condition row selection

These are **core Pandas operations used in almost every data analysis task**. 🚢🚀