# Module 6: Data Manipulation in Pandas
### 🚢 Using the Kaggle Titanic Dataset

## 1️⃣ Introduction

After loading and cleaning a dataset, the next step in data analysis is **data manipulation**.

Data manipulation means **modifying the dataset** to make it suitable for analysis.

Examples of data manipulation:

- Adding new columns
- Removing unnecessary columns
- Renaming columns
- Sorting data

In this module we will learn:

- Adding columns
- Removing columns → `drop()`
- Renaming columns → `rename()`
- Sorting data → `sort_values()` and `sort_index()`

We will practise all these operations on the **real-world Kaggle Titanic dataset**.

## 2️⃣ About the Titanic Dataset

The **Titanic dataset** is one of the most famous beginner datasets in data science.

It contains information about **891 passengers** who were aboard the RMS Titanic.

Key columns:

| Column       | Description                          |
| ------------ | ------------------------------------ |
| `PassengerId`| Unique ID for each passenger         |
| `Survived`   | 0 = Did not survive, 1 = Survived    |
| `Pclass`     | Ticket class (1 = 1st, 2 = 2nd, 3 = 3rd) |
| `Name`       | Passenger name                       |
| `Sex`        | Gender                               |
| `Age`        | Age in years                         |
| `Fare`       | Ticket fare paid                     |
| `Embarked`   | Port of embarkation (C, Q, S)        |

## 3️⃣ Load the Titanic Dataset

We load the dataset directly from a public URL — no file download needed.

In [6]:
import pandas as pd

df = pd.read_csv("Titanic-Dataset.csv")

# Quick overview
print("Shape:", df.shape)
df.head()

Shape: (891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
# Check column names available in the dataset
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

## 4️⃣ Adding a New Column

We can easily add a new column to a DataFrame using:
```python
df["new_column_name"] = values
```

### Example: Add a `FareCategory` column

We will classify each passenger's fare as **'Low'**, **'Medium'**, or **'High'**.

In [8]:
# Add a new 'FareCategory' column based on the Fare value
def categorize_fare(fare):
    if fare < 10:
        return "Low"
    elif fare < 50:
        return "Medium"
    else:
        return "High"

df["FareCategory"] = df["Fare"].apply(categorize_fare)

print(df[["Name", "Fare", "FareCategory"]])

                                                  Name     Fare FareCategory
0                              Braund, Mr. Owen Harris   7.2500          Low
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833         High
2                               Heikkinen, Miss. Laina   7.9250          Low
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  53.1000         High
4                             Allen, Mr. William Henry   8.0500          Low
..                                                 ...      ...          ...
886                              Montvila, Rev. Juozas  13.0000       Medium
887                       Graham, Miss. Margaret Edith  30.0000       Medium
888           Johnston, Miss. Catherine Helen "Carrie"  23.4500       Medium
889                              Behr, Mr. Karl Howell  30.0000       Medium
890                                Dooley, Mr. Patrick   7.7500          Low

[891 rows x 3 columns]

In [9]:
# Add a calculated column: FarePerClass = Fare divided by Pclass
df["FarePerClass"] = df["Fare"] / df["Pclass"]

print(df[["Name", "Fare", "Pclass", "FarePerClass"]].head())

                                                Name     Fare  Pclass  \
0                            Braund, Mr. Owen Harris   7.2500       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833       1
2                             Heikkinen, Miss. Laina   7.9250       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  53.1000       1
4                           Allen, Mr. William Henry   8.0500       3

   FarePerClass
0      2.416667
1     71.283300
2      2.641667
3     53.100000
4      2.683333

## 5️⃣ Removing a Column

Some columns in the Titanic dataset are **not useful for analysis** (e.g., `Cabin` has too many missing values, `Ticket` is just a code).

Use `drop()` to remove them.

```
axis=1 → remove a column
axis=0 → remove a row
```

In [10]:
# Remove the 'Cabin' column — temporary (does NOT change df)
df.drop("Cabin", axis=1).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FareCategory,FarePerClass
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,Low,2.416667
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,High,71.283300
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Low,2.641667
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,High,53.100000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,Low,2.683333

In [11]:
# Remove multiple unnecessary columns PERMANENTLY
df.drop(["Cabin", "Ticket"], axis=1, inplace=True)

print("Columns after dropping:", df.columns.tolist())

Columns after dropping: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'FareCategory', 'FarePerClass']

In [12]:
# Remove a row — e.g. drop the row at index 0
df.drop(0, axis=0).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked,FareCategory,FarePerClass
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C,High,71.283300
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S,Low,2.641667
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S,High,53.100000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S,Low,2.683333
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,8.4583,Q,Low,2.819433

## 6️⃣ Renaming Columns

Some Titanic column names are abbreviated or unclear.
Use `rename()` to give them more descriptive names.

```python
df.rename(columns={"old_name": "new_name"})
```

In [13]:
# Rename columns to more readable names — temporary
df.rename(columns={
    "Pclass": "PassengerClass",
    "SibSp": "SiblingsSpouses",
    "Parch": "ParentsChildren"
}).head()

,PassengerId,Survived,PassengerClass,Name,Sex,Age,SiblingsSpouses,ParentsChildren,Fare,Embarked,FareCategory,FarePerClass
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S,Low,2.416667
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C,High,71.283300
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S,Low,2.641667
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S,High,53.100000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S,Low,2.683333

In [14]:
# Rename PERMANENTLY using inplace=True
df.rename(columns={
    "Pclass": "PassengerClass",
    "SibSp": "SiblingsSpouses",
    "Parch": "ParentsChildren"
}, inplace=True)

print("Updated columns:", df.columns.tolist())

Updated columns: ['PassengerId', 'Survived', 'PassengerClass', 'Name', 'Sex', 'Age', 'SiblingsSpouses', 'ParentsChildren', 'Fare', 'Embarked', 'FareCategory', 'FarePerClass']

In [15]:
df.to_csv("output.csv", index=False)
print("Saved without index.")

Saved without index.

## 7️⃣ Sorting Data — `sort_values()`

Use `sort_values()` to sort the DataFrame by the values of a column.

Default order is **ascending** (lowest to highest).

In [16]:
# Sort passengers by Age — ascending order (youngest first)
df.sort_values("Age")[["Name", "Age", "Fare"]].head(10)

                                Name   Age      Fare
803  Thomas, Master. Assad Alexander  0.42    8.5167
755        Hamalainen, Master. Viljo  0.67   14.5000
644           Baclini, Miss. Eugenie  0.75   19.2583
469    Baclini, Miss. Helene Barbara  0.75   19.2583
78     Caldwell, Master. Alden Gates  0.83   29.0000
831  Richards, Master. George Sibley  0.83   18.7500
305   Allison, Master. Hudson Trevor  0.92  151.5500
386  Goodwin, Master. Sidney Leonard  1.00   46.9000
172     Johnson, Miss. Eleanor Ileen  1.00   11.1333
183        Becker, Master. Richard F  1.00   39.0000

In [17]:
# Sort passengers by Fare — descending order (highest payers first)
df.sort_values("Fare", ascending=False)[["Name", "PassengerClass", "Fare"]].head(10)

                                                Name  PassengerClass      Fare
679               Cardeza, Mr. Thomas Drake Martinez               1  512.3292
258                                 Ward, Miss. Anna               1  512.3292
737                           Lesurer, Mr. Gustave J               1  512.3292
88                        Fortune, Miss. Mabel Helen               1  263.0000
438                                Fortune, Mr. Mark               1  263.0000
341                   Fortune, Miss. Alice Elizabeth               1  263.0000
27                    Fortune, Mr. Charles Alexander               1  263.0000
742            Ryerson, Miss. Susan Parker "Suzette"               1  262.3750
311                       Ryerson, Miss. Emily Borie               1  262.3750
299  Baxter, Mrs. James (Helene DeLaudeniere Chaput)               1  247.5208

### Sorting by Multiple Columns

First sort by **PassengerClass**, then by **Fare** within each class — useful for class-wise fare analysis.

In [18]:
# Sort by PassengerClass first, then by Fare (descending) within each class
df.sort_values(
    ["PassengerClass", "Fare"],
    ascending=[True, False]
)[["Name", "PassengerClass", "Fare"]].head(10)

                                      Name  PassengerClass      Fare
258                       Ward, Miss. Anna               1  512.3292
679     Cardeza, Mr. Thomas Drake Martinez               1  512.3292
737                 Lesurer, Mr. Gustave J               1  512.3292
27          Fortune, Mr. Charles Alexander               1  263.0000
88              Fortune, Miss. Mabel Helen               1  263.0000
341         Fortune, Miss. Alice Elizabeth               1  263.0000
438                      Fortune, Mr. Mark               1  263.0000
311             Ryerson, Miss. Emily Borie               1  262.3750
742  Ryerson, Miss. Susan Parker "Suzette"               1  262.3750
118               Baxter, Mr. Quigg Edmond               1  247.5208

## 8️⃣ `sort_index()` Function

Use `sort_index()` to sort the DataFrame by **row index**.

This is useful after filtering operations where the index becomes out of order.

In [19]:
# Filter first-class passengers — index will be non-sequential
first_class = df[df["PassengerClass"] == 1]
print("First 5 index values after filter:", first_class.index[:5].tolist())

First 5 index values after filter: [1, 3, 6, 11, 23]

In [20]:
# Sort by index — ascending (default)
first_class.sort_index().head()

,PassengerId,Survived,PassengerClass,Name,Sex,Age,SiblingsSpouses,ParentsChildren,Fare,Embarked,FareCategory,FarePerClass
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C,High,71.2833
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S,High,53.1000
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,51.8625,S,High,51.8625
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,26.5500,S,Medium,26.5500
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,35.5000,S,Medium,35.5000

In [21]:
# Sort by index — descending order
first_class.sort_index(ascending=False).head()

,PassengerId,Survived,PassengerClass,Name,Sex,Age,SiblingsSpouses,ParentsChildren,Fare,Embarked,FareCategory,FarePerClass
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,30.0000,C,Medium,30.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.0000,S,Medium,30.0000
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,83.1583,C,High,83.1583
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,5.0000,S,Low,5.0000
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,52.5542,S,High,52.5542

## 🌍 Real-World Example — Full HR-Style Workflow on Titanic

Applying all manipulation steps together in a realistic analysis workflow.

In [39]:
import pandas as pd

# Step 1: Reload a clean copy of the dataset
# url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv("Titanic-Dataset_clean.csv")

print("Original shape:", df.shape)

Original shape: (891, 12)

In [40]:
# Step 2: Remove unnecessary columns
df.drop(["Cabin", "Ticket", "PassengerId"], axis=1, inplace=True)
print("After dropping columns:", df.columns.tolist())

After dropping columns: ['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

In [41]:
# Step 3: Rename columns for clarity
df.rename(columns={
    "Pclass": "PassengerClass",
    "SibSp": "SiblingsSpouses",
    "Parch": "ParentsChildren",
    "Embarked": "Port"
}, inplace=True)
print("Renamed columns:", df.columns.tolist())

Renamed columns: ['Survived', 'PassengerClass', 'Name', 'Sex', 'Age', 'SiblingsSpouses', 'ParentsChildren', 'Fare', 'Port']

In [43]:
# Step 4: Add a new calculated column — Survival label
df["SurvivalStatus"] = df["Survived"].map({0: "Did Not Survive", 1: "Survived"})
print(df[["Name", "Survived", "SurvivalStatus"]].head())
df.to_csv("Titanic-Dataset_final.csv", index=False)

                                                Name Survived SurvivalStatus
0                            Braund, Mr. Owen Harris       No            NaN
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      Yes            NaN
2                             Heikkinen, Miss. Laina      Yes            NaN
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      Yes            NaN
4                           Allen, Mr. William Henry       No            NaN

In [26]:
# Step 5: Sort by Fare — highest paying passengers first
result = df.sort_values("Fare", ascending=False)
print(result[["Name", "PassengerClass", "Fare", "SurvivalStatus"]].head(10))

                                                Name  PassengerClass  \
679               Cardeza, Mr. Thomas Drake Martinez               1
258                                 Ward, Miss. Anna               1
737                           Lesurer, Mr. Gustave J               1
88                        Fortune, Miss. Mabel Helen               1
438                                Fortune, Mr. Mark               1
341                   Fortune, Miss. Alice Elizabeth               1
27                    Fortune, Mr. Charles Alexander               1
742            Ryerson, Miss. Susan Parker "Suzette"               1
311                       Ryerson, Miss. Emily Borie               1
299  Baxter, Mrs. James (Helene DeLaudeniere Chaput)               1

         Fare SurvivalStatus
679  512.3292            NaN
258  512.3292            NaN
737  512.3292            NaN
88   263.0000            NaN
438  263.0000            NaN
341  263.0000            NaN
27   263.0000            NaN
742  262.3750            NaN
311  262.3750            NaN
299  247.5208            NaN

## 💡 Important Tips

| Operation              | Syntax                                             |
| ---------------------- | -------------------------------------------------- |
| Add column             | `df["col"] = values`                               |
| Calculated column      | `df["col"] = df["other"] * value`                  |
| Remove column          | `df.drop("col", axis=1)`                           |
| Remove permanently     | `df.drop("col", axis=1, inplace=True)`             |
| Rename column          | `df.rename(columns={"old": "new"})`                |
| Sort ascending         | `df.sort_values("col")`                            |
| Sort descending        | `df.sort_values("col", ascending=False)`           |
| Sort by multiple cols  | `df.sort_values(["col1", "col2"])`                 |
| Sort by index          | `df.sort_index()`                                  |

## 📋 Summary of Module 6

In this module we learned how to **manipulate data in Pandas** using the real-world **Titanic dataset**.

Concepts covered:

- **Adding columns** → `df["new_col"] = values` or calculated columns
- **Removing columns** → `df.drop("col", axis=1)`
- **Renaming columns** → `df.rename(columns={"old": "new"})`
- **Sorting by values** → `df.sort_values("col")`
- **Sorting by multiple columns** → `df.sort_values(["col1", "col2"])`
- **Sorting by index** → `df.sort_index()`

These operations are **essential for organizing and preparing real-world datasets for analysis**. 🚢🚀