# Module 3: Exploring DataFrames (Basic Data Inspection)

## 1️⃣ Introduction

After loading or creating a dataset in Pandas, the **first step in data analysis** is to **explore the dataset**.

This process is called **Data Inspection** or **Data Exploration**.

It helps us quickly understand:

- What the dataset looks like
- How many rows and columns it has
- What type of data is present
- Whether there are missing values

Pandas provides several **built-in functions** that allow us to explore data easily:

- `head()`
- `tail()`
- `info()`
- `describe()`
- `shape`
- `columns`
- `index`

These functions are used **daily by data analysts**.

## 2️⃣ Why This Concept is Important

In real-world data analysis, datasets can contain **thousands or millions of rows**.

For example: Customer data, Sales data, Financial transactions, Website analytics.

Before performing analysis, we must understand:

✔ Data structure  
✔ Number of records  
✔ Data types  
✔ Missing values  

Using Pandas inspection functions helps analysts **quickly understand the dataset**.

## 3️⃣ Example Dataset

Let's create a simple DataFrame that we'll use throughout this module.

In [2]:
import pandas as pd


df = pd.read_csv("Titanic-Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## 4️⃣ `head()` Function

### Purpose

Displays the **first 5 rows** of the dataset by default.

### Explanation

- Shows the **top rows of the dataset**
- Helps us quickly see the **structure of the data**

In [3]:
# Display the first 5 rows (default)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Custom Rows

You can also specify the number of rows to display.

In [4]:
# Display only the first 3 rows
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

## 5️⃣ `tail()` Function

### Purpose

Displays the **last 5 rows** of the dataset by default.

Useful for checking the end of the dataset.

In [5]:
# Display the last 5 rows (default)
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [6]:
# Display only the last 2 rows
df.tail(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

## 6️⃣ `info()` Function

### Purpose

Provides **information about the dataset**.

`df.info()` shows:

- Number of rows
- Number of columns
- Column names
- Data types
- Non-null values
- Memory usage

This function is **very useful for detecting missing data**.

In [7]:
# Get detailed information about the DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

## 7️⃣ `describe()` Function

### Purpose

Shows **statistical summary of numerical columns**.

`describe()` calculates:

| Statistic | Meaning            |
| --------- | ------------------ |
| count     | number of values   |
| mean      | average value      |
| std       | standard deviation |
| min       | minimum value      |
| max       | maximum value      |

This helps understand **data distribution**.

In [8]:
# Get statistical summary of numerical columns
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## 8️⃣ `shape` Attribute

### Purpose

Shows the **number of rows and columns** as a tuple `(rows, columns)`.

In [9]:
# Get the shape of the DataFrame
print(df.shape)
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

(891, 12)
Rows: 891, Columns: 12

## 9️⃣ `columns` Attribute

### Purpose

Displays **all column names** in the DataFrame.

In [10]:
# Get all column names
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

## 🔟 `index` Attribute

### Purpose

Shows the **row index values**.

Row numbers start from **0 and go up to 4** in our example.

In [11]:
# Get the row index
df.index

RangeIndex(start=0, stop=891, step=1)

## 💡 Important Tips

✔ **Always run these commands first** when analyzing a new dataset:

```
df.head()
df.info()
df.describe()
```

✔ They help detect **data problems early**

✔ These functions are used **in almost every data analysis project**

## 📋 Summary of Module 3

In this module we learned how to **inspect and explore a dataset** using Pandas.

| Function / Attribute | Purpose                        |
| -------------------- | ------------------------------ |
| `head()`             | Display first rows              |
| `tail()`             | Display last rows               |
| `info()`             | Dataset structure & types       |
| `describe()`         | Statistical summary             |
| `shape`              | Number of rows & columns        |
| `columns`            | Column names                    |
| `index`              | Row labels                      |

These are **fundamental tools used by every data analyst**. 🚀